   name: Semgrep Analysis

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     semgrep:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up PHP
           run: |
             sudo apt-get update
             sudo apt-get install -y php

         - name: Install Semgrep
           run: |
             pip install semgrep

         - name: Run Semgrep and generate SARIF report
           run: |
             semgrep --config "p/ci" . -o semgrep-results.sarif --sarif || exit 1

         - name: Upload SARIF report
           uses: github/codeql-action/upload-sarif@v1
           with:
             sarif_file: semgrep-results.sarif
